# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79bc7375bfb55c618f5fbcb80d85dc0ef017a671c23a303fccf168ef64887b313fcb9c6a2c314dabacb6e66d0468f453b8106c8da29d3c3fbfe197048f307f3f

test:
  secret_key_base: 904d7cbb414692eddc8572e561f04f7a3ce7beed07296c248874f854ec095132158917a8a9bf6bb742d24505591e4780e77be5f272b563f3e822f9afd587709f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
